# Everything required for the ecosystem to run is dockerized by this file as a docker-compose.
version: '3.3'

services:
  # This is not for the applications, user by sonarqube & pact
  postgres_db:
    image: postgres:10.11
    container_name: postgres_db
    restart: unless-stopped
    networks:
      - pipeline
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data
      - ./dkr/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  sonar:
    image: sonarqube
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
    container_name: sonarqube
    restart: unless-stopped
    networks:
      - pipeline
    depends_on:
      - postgres_db
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres_db:5432/sonardb
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nofile:
         soft: 65536
         hard: 65536

  # this is annoying docker dind should be called as `docker`
  docker:
    image: docker:dind
    networks:
      - pipeline
    ports:
      - "2376:2376"
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

  jenkins:
    image: jenkinsci/blueocean
    restart: unless-stopped
    networks:
      - pipeline
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  pact-broker:
    image: pactfoundation/pact-broker
    restart: unless-stopped
    networks:
      - pipeline
    ports:
      - "9292:9292"
    depends_on:
      - postgres_db
    environment:
      PACT_BROKER_PORT: "9292"
      PACT_BROKER_DATABASE_URL: "postgres://pact:pact@postgres_db:5432/pactdb"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG

networks:
  pipeline:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-home:
  jenkins-docker-certs:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
  postgresql:
  postgresql-data:
