spring:
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://localhost:5432/trisolar"
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  flyway:
    # the /dev/db/migration can also be defined in application-dev.yml
    locations: classpath:/db/migration,classpath:/dev/db/migration

# All actuator/micrometer related stuff here.
management:
  server:
    port: 8181