pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Unit & Integration Tests') {
      steps {
        script {
          try {
            sh './trisolar/gradlew -b ./trisolar/build.gradle clean build sonarqube \
                          -Dsonar.host.url=http://sonarqube:9000 \
                          -Dsonar.login=39bd6cb5337b9f6abd829ef57171aedbb39a2f77 \
                          -Dsonar.projectKey=TRISOLAR --info'
          } finally {
            junit '**/build/test-results/test/*.xml'
          }
        }
      }
    }

    stage('Dockerize') {
      steps {
        script {
          sh './trisolar/gradlew docker'
        }
      }
    }
  }
}
